import openai
import os

# TAKE THE JOB DESCRIPTION AND GET THE DATA
# TAKE THE DATA AND USE IT TO CREATE THE COVER
# ORGANIZE THE  COVER INTO THE FILESYSTEM
# TAKE THE DATA AND CREATE THE TAILORED RESUME
# ORGANIZE THE RESUME INTO THE FILESYSTEM

